### ISSUE TITLE
Not compatible with swift 2.0

### ISSUE THREAD

**Issue by deepika1203** [balram3429/btSimplePopUp#8]
I could not create the actions array with dispatch_block_t in swift 2.0
The below code works well in Swift1.2, but not in Swift 2.0

        var menuView: btSimplePopUP!
        let imgs = [UIImage(named: "pickImage.png")!,
                UIImage(named: "takePicture.png")!,
                UIImage(named: "pickVideo.png")!,
                UIImage(named: "shootVideo.png")!,
                UIImage(named: "recordAudio.png")!,
                UIImage(named: "quit.png")!] as NSArray
        
            let titles = ["Images",
                "Capture",
                "Videos",
                "Shoot",
                "Record",
                "Cancel"] as NSArray
        
            let actions: [dispatch_block_t] = [{self.pickImages()},
                {self.takePicture()},
                {self.pickVideos()},
                {self.shootVideo()},
                {self.recordAudio()},
                {self.closeView()}]
        
            menuView = btSimplePopUP(itemImage: imgs as [AnyObject],
                andTitles: titles as [AnyObject],
                andActionArray:  actions as NSArray as [AnyObject],
                addToViewController: self)
            
                self.view.addSubview(menuView)
                menuView.show(BTPopUpAnimation.UPAnimateWithFade)

Is there any way to use btSimplePopUp in Swift 2.0?

**Comment by balram3429** [comment]
For thisI believe delegates would be great instead of Blocks of action arrays.
1. Conform to protocol `btSimplePopUpDelegate`.
2. Check the new code & use the `-(instancetype)initWithItemImage:(NSArray *)items andTitles:(NSArray *)titleArray andActionArray:(NSArray *)actionArray addToViewController:(UIViewController*)sender` and pass `actionArray` as nil.
3. Implement the delegate method `-(void)btSimplePopUP:(btSimplePopUP *)popUp didSelectItemAtIndex:(NSInteger)index;` to get the index of selected item.

As of now if you pass array of action blocks, it will be initialised with blocks, passing nil will invoke the delegate implementation. Check the example screen.

Thanks,
Balram Tiwari

**Comment by deepika1203** [comment]
Thanks for updating the code. But I am getting the following error `Use of undeclared type
 'btSimplePopUP'` after adding `btSimplePopUpDelegate`

![screenshot 2015-11-13 19 40 32](https://cloud.githubusercontent.com/assets/15829511/11147839/cac9a034-8a3e-11e5-9059-517bb3acbc6f.png)

**Comment by deepika1203** [comment]
Thanks for updating the code!
